query GetPokemonById($where: pokemon_bool_exp) {
  pokemon(where: $where) {
    ...PokemonDetailsFragment
  }
}

query SearchPokemons($q: String!, $limit: Int!, $offset: Int!) {
  pokemon(
    where: {name: {_ilike: $q}}
    limit: $limit
    offset: $offset
    order_by: {id: asc}
  ) {
    ...PokemonDetailsFragment
  }
}
